### ISSUE TITLE
Feature Request: Add ability to drag the slide bar to fast forward/rewind with Spotify

### ISSUE THREAD

**Issue by MelissaManley97** [Team-NullPointer/Clementine#13]
### Before posting

Please follow the steps below and check the boxes with [x] once you did the step.

- [x] I checked the issue tracker for similar issues
- [x] I checked the [changelog](https://github.com/clementine-player/Clementine/blob/master/Changelog) if the issue is already resolved
- [x] I tried the latest Clementine build from [here](https://builds.clementine-player.org/)

### System information

Please provide information about your system and the version of Clementine used.

- Operating System: Latest version of Ubuntu
- Clementine version: Latest release and latest build with last commit being: 27bf50d

### Expected behavior / actual behavior

Expected behavior: 
It is expected that when playing a song through Spotify, the user could drag the slide bar depicted below to fast forward and/or rewind the song. This is a feature possible in Clementine with songs that are not obtained through Spotify, as shown below.
![image](https://cloud.githubusercontent.com/assets/25350560/23537877/0be5683a-ff9d-11e6-8334-9add1769a78b.png)
- The time the song is expected to rewind/fast forward to and how much the user wants to rewind/fast forward (in this case, -0.01 seconds) is shown.

Actual behavior:
When the user plays a Spotify song, they are not able to drag the slide bar to fast forward/rewind the specific song. When the user attempts to drag the slide bar, nothing occurs.
![image](https://cloud.githubusercontent.com/assets/25350560/23537893/2999e61c-ff9d-11e6-9aab-8c9dce4d6b1f.png)

An update to include this ability to fast forward/rewind a specific song would
be extremely useful for Spotify listeners who use Clementine.

**Comment by gdolphy2015** [comment]
#2503

**Comment by ghost** [comment]
https://github.com/Team-NullPointer/Clementine/blob/91815493278ca07003ec42d2bca94a54fc71d984/src/internet/spotify/spotifyserver.cpp#L272

**Comment by ghost** [comment]
Seeking feature is deprecated. Can't fix.
