### ISSUE TITLE
issues with "shuffle album" mode

### ISSUE THREAD

**Issue by MelissaManley97** [Team-NullPointer/Clementine#5]
[#5624](https://github.com/clementine-player/Clementine/issues/5624)

**Comment by gdolphy2015** [comment]
Wasn't able to replicate, was possibly fixed already.

**Comment by GitHorst** [comment]
@gdolphy2015 This is not resolved. It is still exactly the same behavior as described in my original report. MacOS (12.2.1) with Clementine 1.3.1 -- i.e. new macOS but same Clementine version as in the original issue report.

**Comment by GitHorst** [comment]
@gdolphy2015 and i checked: it is exactly the same behavior on my other machine with Linux Mint 19.2
