### ISSUE TITLE
Make shuffling more random

### ISSUE THREAD

**Issue by MelissaManley97** [Team-NullPointer/Clementine#8]
[#5201](https://github.com/clementine-player/Clementine/issues/5201)

Not sure if this would be considered a bug or an enhancement.

**Comment by gdolphy2015** [comment]
Seems that swapping these[ two lines ](https://github.com/clementine-player/Clementine/blob/e5ab3e786f9adde12cec3cc90cfe8c1cc6b06320/src/core/player.cpp#L397-L398)fixes the issue
